version: '3.9'

services:
  gitlab-dind:
    image: docker:${DIND_IMAGE_TAG}
    environment:
      DOCKER_TLS_CERTDIR: ""
    networks:
      gitlab-net:
    volumes:
      - dind-vol:/var/lib/docker
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    security_opt:
      - seccomp=unconfined
    deploy:
      mode: replicated
      replicas: ${DIND_REPLICAS:-1}
      restart_policy:
        delay: ${DIND_RESTART_DELAY:-5s}
      update_config:
        delay: ${DIND_UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${DIND_RESOURCES_LIMITS_CPUS:-4}'
          memory: ${DIND_RESOURCES_LIMITS_MEMORY:-4G}
        reservations:
          cpus: '${DIND_RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${DIND_RESOURCES_RESERVATIONS_MEMORY:-1G}

  gitlab-runner:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    environment:
      CONFIG_FILE:
      DOCKER_HOST: ${RUNNER_DOCKER_HOST}
    networks:
      gitlab-net:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - config-vol:/etc/gitlab-runner
      - work-vol:/home/gitlab-runner
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-32M}

volumes:
  work-vol:
    name: ${WORK_VOL_NAME}

  dind-vol:
    name: ${DIND_VOL_NAME}

networks:
  gitlab-net:
    name: ${GITLAB_NET_NAME}
    driver: ${GITLAB_NET_DRIVER}
    external: true
