version: '3.9'

services:
  gitlab-runner:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    entrypoint: /bin/sh
    command: >
      -c "
        docker network create ${GITLAB_NET_NAME} || true;
        docker run --rm -d
          --name gitlab-dind
          -e DOCKER_TLS_CERTDIR=''
          -v gitlab-runner-dind-vol:/var/lib/docker
          --network ${GITLAB_NET_NAME}
          --privileged
          --restart always
          --cpus ${DIND_CPUS:-4}
          --memory ${DIND_MEMORY:-4G}
          --memory-reservation ${DIND_MEMORY_RESERVATION:-1G}
          docker:${DIND_IMAGE_TAG}
          --tls=false;
        /usr/bin/dumb-init
          /entrypoint
            run
            --user=gitlab-runner
            --working-directory=${WORK_DIR}"
    environment:
      CONFIG_FILE:
      DOCKER_HOST: ${RUNNER_DOCKER_HOST}
    networks:
      gitlab-net:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - config-vol:${CONFIG_DIR}
      - work-vol:${WORK_DIR}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-32M}

volumes:
  work-vol:
    name: ${WORK_VOL_NAME}

  dind-vol:
    name: ${DIND_VOL_NAME}

networks:
  gitlab-net:
    name: ${GITLAB_NET_NAME}
    driver: ${GITLAB_NET_DRIVER}
    external: true
